#!/bin/bash
NAME=${PWD##*/}
# replace theducknight with your duckiebot's hostname
docker -H theducknight.local stop jupyter-node
docker -H theducknight.local rm jupyter-node
docker -H theducknight.local run -d -v /data/notebooks:/data/notebooks --net=host --name jupyter-node duckietown/dt-$NAME:HEAD-arm32v7 #/bin/sh
